import nodemailer from "nodemailer";

export async function sendContactEmail(req, res) {
	const { name, email, subject, message } = req.body;

	if (!name || !email || !message) {
		res.status(400).json({
			message: "Name, email, and message are required fields",
		});
		return;
	}

	try {
		const transporter = nodemailer.createTransport({
			service: "gmail",
			host: "smtp.gmail.com",
			port: 587,
			secure: false,
			auth: {
				user: "givacreations2003@gmail.com",
				pass: process.env.GMAIL_APP_PASSWORD,
			},
		});

		const mailOptions = {
			from: `"TechNova Contact Form" <skyrek7@gmail.com>`,
			to: "givacreations2003@gmail.com",
			subject: `Contact Form Inquiry: ${subject || "General Inquiry"}`,
			text: `Name: ${name}\nEmail: ${email}\n\nMessage:\n${message}`,
			html: `
				<div style="font-family: Arial, sans-serif; padding: 20px; color: #333; max-width: 600px; border: 1px solid #eee; border-radius: 10px;">
					<h2 style="color: #0f172a; border-bottom: 2px solid #38D5BE; padding-bottom: 10px;">New Contact Form Submission</h2>
					<p style="font-size: 14px;">You have received a new inquiry from the TechNova contact form.</p>
					<div style="background-color: #f8fafc; padding: 15px; border-radius: 8px; margin: 20px 0;">
						<p style="margin: 5px 0;"><strong>Name:</strong> ${name}</p>
						<p style="margin: 5px 0;"><strong>Email:</strong> <a href="mailto:${email}">${email}</a></p>
						<p style="margin: 5px 0;"><strong>Subject:</strong> ${subject || "General Inquiry"}</p>
					</div>
					<h3 style="color: #0f172a; margin-top: 20px;">Message:</h3>
					<p style="font-size: 14px; line-height: 1.6; background-color: #f8fafc; padding: 15px; border-radius: 8px; white-space: pre-wrap;">${message}</p>
					<footer style="margin-top: 30px; font-size: 12px; color: #64748b; border-top: 1px solid #eee; padding-top: 10px; text-align: center;">
						This email was auto-generated by the TechNova Contact Form.
					</footer>
				</div>
			`,
		};

		await transporter.sendMail(mailOptions);

		res.json({
			message: "Message sent successfully",
		});
	} catch (error) {
		console.error("Email sending error:", error);
		res.status(500).json({
			message: "Failed to send email",
			error: error.message,
		});
	}
}
